name: Incremental Static Regeneration
on:
  workflow_dispatch:
    inputs:
      extension:
        description: "Id of the extension to upload"
        required: true
        default: 'example'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  CLOUDFRONT_ARN: ${{ secrets.CLOUDFRONT_ARN }}
  NEXT_PUBLIC_REST_API_URL: "https://api.roamjs.com"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  NEXT_PUBLIC_CLERK_FRONTEND_API: clerk.roamjs.com
  NEXT_PUBLIC_CLERK_SIGN_IN: https://accounts.roamjs.com/sign-in

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:next
      - name: Upload
        run: npm run upload -- ${{ github.event.inputs.extension }}
