name: Push Site to Master
on:
  push:
    branches: master
    paths:
      - "components/**"
      - "public/**"
      - "pages/**"
      - "package.json"
      - ".github/workflows/master_index.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  NEXT_PUBLIC_FLOSS_TENANT: RoamJS
  NEXT_PUBLIC_REST_API_URL: "https://api.roamjs.com"
  NEXT_PUBLIC_FLOSS_API_URL: "https://api.davidvargas.me"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  NEXT_PUBLIC_CLERK_FRONTEND_API: clerk.roamjs.com
  NEXT_PUBLIC_CLERK_SIGN_IN: https://accounts.roamjs.com/sign-in

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:next
      - name: Upload
        run: |
          aws s3 sync out s3://roamjs.com
          for filename in $(find out -type f -name "*.html"); do
              HTML=$(echo $filename | cut -f 1 -d '.' | cut -d '/' -f 2-)
              aws s3 cp $filename s3://roamjs.com/$HTML --content-type "text/html"
          done
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
