name: Push Extensions to Master
on:
  push:
    branches: master
    paths:
      - "src/components/**"
      - "src/entries/**"
      - "src/entry-helpers.ts"
      - "webpack.production.config.js"
      - ".github/workflows/master.yaml"
      - "package.json"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  ROAMJS_VERSION: production
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  GIPHY_KEY: ${{ secrets.GIPHY_KEY }}
  REST_API_URL: https://api.roamjs.com
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Build
        run: npm run build
        env:
          IS_LEGACY: true
      - name: Upload Old
        run: aws s3 sync build s3://roam.davidvargas.me/master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OLD_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OLD_AWS_ACCESS_SECRET }}
      - name: Build
        run: npm run build
      - name: Upload
        run: aws s3 sync build s3://roamjs.com
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roam.davidvargas.me'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
