name: Push Site to Master
on:
  push:
    branches: master
    paths:
      - "docs"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: brew install mkdocs
      - name: Build
        run: mkdocs build --clean
      - name: Upload
        run: aws s3 sync dist s3://roam.davidvargas.me
