name: Push Extensions From PR
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  ROAMJS_VERSION: ${{ github.event.number }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  GIPHY_KEY: ${{ secrets.GIPHY_KEY }}
  REST_API_URL: https://${{ secrets.REST_API_ID }}.execute-api.us-east-1.amazonaws.com/production

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: Build
        run: npm run build:pr
      - name: Upload
        run: aws s3 sync build s3://roamjs.com/${{github.event.number}}
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/${{ github.event.number }}/*"
