name: Push Site to Branch
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  APP_BASE_PATH: /${{github.event.number}}
  NEXT_PUBLIC_REST_API_ID: ${{ secrets.REST_API_ID }}
  NEXT_PUBLIC_FLOSS_API_URL: "https://${{ secrets.FLOSS_API_ID }}.execute-api.us-east-1.amazonaws.com/production"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
  NEXT_PUBLIC_CLERK_SIGN_IN: ${{ secrets.CLERK_SIGN_IN }}
  NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:next
      - name: Upload
        run: |
          aws s3 sync out s3://roamjs.com$APP_BASE_PATH
          for filename in $(find out -type f -name "*.html"); do
              HTML=$(echo $filename | cut -f 1 -d '.' | cut -d '/' -f 2-)
              aws s3 cp $filename s3://roamjs.com$APP_BASE_PATH/$HTML --content-type "text/html"
          done
      - name: Invalidate Cache
        run: |
          CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='roamjs.com'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
